version: '3.7'

services:
  web_server:
    build: .
    ports:
      - 5003:80
    depends_on:
      - postgres
    # restart: unless-stopped

  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opentrafficeye
      - PGDATA=/var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
